<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Heewon Yoon" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<pre class="r"><code>covid &lt;- read.csv(file = &quot;covid19.csv&quot;,
                  header = TRUE, 
                  quote=&quot;\&quot;&quot;, 
                  stringsAsFactors= TRUE, 
                 strip.white = TRUE)</code></pre>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>The dataset I chose shows the death counts for influenza, pneumonia, and COVID-19 reported to National Center for Health Statistics (NCHS) during the year of 2020 to 2021. The data is organized by date, state, and age group. For my categorical variable, I will be using the age groups, which splits into 4 groups including all age, 0-17 years, 18-64 years, and 65 years and over. For the binary variable, I will be using the year that the data was collected, which divides into 2020 and 2021. For the numerical variables, I will be using the COVID-19 deaths, Influenza deaths, and Pneumonia deaths. The deaths were recorded weekly starting from 1/4/2020 through 4/24/2021 for each state and age groups, and there are total of 17388 observations.</p>
</div>
<div id="manova-test" class="section level1">
<h1>1. MANOVA Test</h1>
<pre class="r"><code>man1&lt;-manova(cbind(COVID.19.Deaths,Pneumonia.Deaths,Influenza.Deaths)~Age.Group, data=covid)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Age.Group 3 0.042663 47.731 9 29778 &lt; 2.2e-16 ***
## Residuals 9926
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>## Response COVID.19.Deaths :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Age.Group 3 2.8548e+08 95158377 69.178 &lt; 2.2e-16 ***
## Residuals 9926 1.3654e+10 1375562
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Pneumonia.Deaths :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Age.Group 3 231867918 77289306 107.12 &lt; 2.2e-16 ***
## Residuals 9926 7161941841 721534
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Influenza.Deaths :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Age.Group 3 103469 34490 44.872 &lt; 2.2e-16 ***
## Residuals 9926 7629302 769
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## 7458 observations deleted due to missingness</code></pre>
<pre class="r"><code>covid1 &lt;- na.omit(covid)

library(rstatix)
group &lt;- covid1$Age.Group
DVs &lt;- covid1 %&gt;% select(COVID.19.Deaths,Pneumonia.Deaths,Influenza.Deaths)
sapply(split(DVs,group), mshapiro_test)</code></pre>
<pre><code>## 0-17 years 18-64 years 65 years and over All Ages
## statistic 0.1363562 0.3452072 0.2023092 0.3342874
## p.value 1.035559e-63 1.824636e-64 1.259922e-72
3.28008e-69</code></pre>
<pre class="r"><code>lapply(split(DVs,group), cov)</code></pre>
<pre><code>## $`0-17 years`
## COVID.19.Deaths Pneumonia.Deaths Influenza.Deaths
## COVID.19.Deaths 1.17743839 1.551354 0.02557246
## Pneumonia.Deaths 1.55135387 6.208294 2.33940243
## Influenza.Deaths 0.02557246 2.339402 1.98702427
##
## $`18-64 years`
## COVID.19.Deaths Pneumonia.Deaths Influenza.Deaths
## COVID.19.Deaths 149689.568 111369.199 1176.0750
## Pneumonia.Deaths 111369.199 89183.965 1758.1961
## Influenza.Deaths 1176.075 1758.196 330.2854
##
## $`65 years and over`
## COVID.19.Deaths Pneumonia.Deaths Influenza.Deaths
## COVID.19.Deaths 2188417.68 1501595.38 7994.1804
## Pneumonia.Deaths 1501595.38 1119636.85 11580.5164
## Influenza.Deaths 7994.18 11580.52 815.1672
##
## $`All Ages`
## COVID.19.Deaths Pneumonia.Deaths Influenza.Deaths
## COVID.19.Deaths 3324054.9 2325866.75 14866.600
## Pneumonia.Deaths 2325866.8 1762885.11 22234.056
## Influenza.Deaths 14866.6 22234.06 2058.999</code></pre>
<pre class="r"><code>covid1 %&gt;% group_by(Age.Group) %&gt;% summarize(mean(COVID.19.Deaths),mean(Pneumonia.Deaths), mean(Influenza.Deaths))</code></pre>
<pre><code>## # A tibble: 4 x 4
## Age.Group `mean(COVID.19.Deaths)`
`mean(Pneumonia.Deaths)` `mean(Influenza.Deaths)`
## &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 0-17 years 0.183 0.471 0.128
## 2 18-64 years 119.  108.  3.28
## 3 65 years and over 336.  299.  5.15
## 4 All Ages 408.  370.  8.60</code></pre>
<pre class="r"><code>pairwise.t.test(covid1$COVID.19.Deaths,covid1$Age.Group, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: covid1$COVID.19.Deaths and covid1$Age.Group
##
## 0-17 years 18-64 years 65 years and over
## 18-64 years 0.0063 - -
## 65 years and over 1.4e-15 2.3e-08 -
## All Ages &lt; 2e-16 1.0e-13 0.0513
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(covid1$Pneumonia.Deaths,covid1$Age.Group, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: covid1$Pneumonia.Deaths and covid1$Age.Group
##
## 0-17 years 18-64 years 65 years and over
## 18-64 years 7e-04 - -
## 65 years and over &lt; 2e-16 9.2e-12 -
## All Ages &lt; 2e-16 &lt; 2e-16 8e-03
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(covid1$Influenza.Deaths,covid1$Age.Group, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: covid1$Influenza.Deaths and covid1$Age.Group
##
## 0-17 years 18-64 years 65 years and over
## 18-64 years 0.0023 - -
## 65 years and over 4.3e-07 0.0413 -
## All Ages &lt; 2e-16 6.1e-09 7.2e-05
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>0.05/22</code></pre>
<pre><code>## [1] 0.002272727</code></pre>
<pre class="r"><code>1- 0.95^22</code></pre>
<pre><code>## [1] 0.6764665</code></pre>
<p>A one-way MANOVA was conducted to determine the effect of the age groups (All age, 0-17,18-65, and 65+) on three dependent variables (COVID deaths, Pneumonia deaths, Influenza deaths). Multivariate normality and relative homogeneity were revealed through multivariate normality assumption test and covariance matrices. Significant differences were found among 4 age groups for at least one of the dependent variables. 1 MANOVA test, 3 ANOVAs, and 18 t tests (22 tests) were performed. The probability that you have made at least one type I error is 0.6764. The significance level should be 0.00227 to keep the overall type I error rate at .05.
Some of the MANOVA assumptions include random samples, multivariate normality, homogeneity, linear relationships, no extreme univariate/multivariate outliers. Some of the assumptions were probably violated.</p>
</div>
<div id="randomization-test" class="section level1">
<h1>2. Randomization Test</h1>
<pre class="r"><code>covid_19 &lt;- c(1384,1055,928,753,563,442,349,200,92,40)
pneumonia &lt;- c(991,795,747,645,526,418,368,234,122,46)


deaths &lt;-data.frame(disease=c(rep(&quot;covid_19&quot;,10),rep(&quot;pneumonia&quot;,10)),deathnumber=c(covid_19,pneumonia))
head(deaths)</code></pre>
<pre><code>##    disease deathnumber
## 1 covid_19        1384
## 2 covid_19        1055
## 3 covid_19         928
## 4 covid_19         753
## 5 covid_19         563
## 6 covid_19         442</code></pre>
<pre class="r"><code>new&lt;-data.frame(disease=sample(deaths$disease),deathnumber=deaths$deathnumber)
new%&gt;%group_by(disease)%&gt;%
   summarize(means=mean(deathnumber))%&gt;%summarize(`mean_diff`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1     -22.2</code></pre>
<pre class="r"><code>rand_dist&lt;-vector() 

for(i in 1:5000){
new&lt;-data.frame(disease=sample(deaths$disease),deathnumber=deaths$deathnumber) 
rand_dist[i]&lt;-mean(new[new$disease==&quot;covid_19&quot;,]$deathnumber)-   
              mean(new[new$disease==&quot;pneumonia&quot;,]$deathnumber)}

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = c(-200.8, 200.8),col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;208.8 | rand_dist &lt; -200.8)</code></pre>
<pre><code>## [1] 0.2276</code></pre>
<p>The null hypothesis is that the mean number of deaths for past 3 months (February to April) is the same for COVID 19 and Pneumonia. The alternative hypothesis is that the mean number of deaths is different for COVID 19 and Pneumonia. After taking 5000 random permutations, I made a histogram. The two-tailed p-value was 0.227, so I failed to reject the null hypothesis. This means that I failed to reject that the mean number of deaths is the same for COVID 19 and Pneumonia.</p>
</div>
<div id="linear-regression-model" class="section level1">
<h1>3. Linear Regression Model</h1>
<pre class="r"><code>fit&lt;-lm(Total.Deaths ~ COVID.19.Deaths*Age.Group, data=covid1); summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = Total.Deaths ~ COVID.19.Deaths * Age.Group,
data = covid1)
##
## Residuals:
## Min 1Q Median 3Q Max
## -35705 -1017 -398 -12 58992
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 29.22 111.19 0.263 0.7927
## COVID.19.Deaths 87.58 101.07 0.866 0.3863
## Age.Group18-64 years 429.53 149.59 2.871 0.0041 **
## Age.Group65 years and over 1181.56 142.44 8.295 &lt;2e-16
***
## Age.GroupAll Ages 1556.13 142.19 10.944 &lt;2e-16 ***
## COVID.19.Deaths:Age.Group18-64 years -81.62 101.07
-0.808 0.4194
## COVID.19.Deaths:Age.Group65 years and over -83.22 101.07
-0.823 0.4103
## COVID.19.Deaths:Age.GroupAll Ages -82.84 101.07 -0.820
0.4125
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 4265 on 8338 degrees of freedom
## Multiple R-squared: 0.6685, Adjusted R-squared: 0.6683
## F-statistic: 2402 on 7 and 8338 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>coviddeaths_c &lt;- covid1$COVID.19.Deaths - mean(covid1$COVID.19.Deaths, 
    na.rm = TRUE)
fitt &lt;- lm(Total.Deaths ~ coviddeaths_c * Age.Group, data = covid1)
summary(fitt)</code></pre>
<pre><code>##
## Call:
## lm(formula = Total.Deaths ~ coviddeaths_c * Age.Group,
data = covid1)
##
## Residuals:
## Min 1Q Median 3Q Max
## -35705 -1017 -398 -12 58992
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 21428.77 24679.10 0.868 0.385
## coviddeaths_c 87.58 101.07 0.866 0.386
## Age.Group18-64 years -19514.54 24679.31 -0.791 0.429
## Age.Group65 years and over -19154.21 24679.26 -0.776
0.438
## Age.GroupAll Ages -18685.27 24679.26 -0.757 0.449
## coviddeaths_c:Age.Group18-64 years -81.62 101.07 -0.808
0.419
## coviddeaths_c:Age.Group65 years and over -83.22 101.07
-0.823 0.410
## coviddeaths_c:Age.GroupAll Ages -82.84 101.07 -0.820
0.412
##
## Residual standard error: 4265 on 8338 degrees of freedom
## Multiple R-squared: 0.6685, Adjusted R-squared: 0.6683
## F-statistic: 2402 on 7 and 8338 DF, p-value: &lt; 2.2e-16</code></pre>
<p>For every 1-unit increase in COVID.19.Deaths, the predicted Total.Deaths increases by 87.58. The Age.Group of 18-64 years with zero COVID.19.Deaths have predicted Total.Deaths that is 429 higher than the Age.Group of 0-17 years with zero COVID.19.Deaths. The Age.Group of 65 years and over with zero COVID.19.Deaths have predicted Total.Deaths that is 19514.54 higher than the Age.Group of 0-17 years with zero COVID.19.Deaths. When I mean center the data, it shows that the Age.Group of 18-64 years with average COVID.19.Deaths have predicted Total.Deaths that is 19154.21 less than the Age.Group of 0-17 years with average COVID.19.Deaths. The Age.Group of 65 years and over with average COVID.19.Deaths have predicted Total Deaths that is 17149 lower than the Age.Group of 0-17 years with average COVID.19.Deaths. The slope of Covid Deaths on Total Deaths for the Age Group 18-64 years was 81.62 less than the Age Group 0-17.</p>
<div id="plot" class="section level2">
<h2>Plot</h2>
<pre class="r"><code>covid1 %&gt;% select(Total.Deaths, COVID.19.Deaths, Age.Group) %&gt;% na.omit %&gt;% 
    ggplot(aes(COVID.19.Deaths, Total.Deaths, color = Age.Group)) + 
    geom_point() + geom_smooth(method = &quot;lm&quot;) + geom_vline(xintercept = mean(covid1$COVID.19.Deaths, 
    na.rm = T), lty = 2)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-7-1.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="assumptions-and-robust-standard-errors" class="section level2">
<h2>Assumptions and Robust Standard Errors</h2>
<pre class="r"><code>#install.packages(&quot;lmtest&quot;)
library(lmtest)
fit2 &lt;-lm(Total.Deaths ~ COVID.19.Deaths*Age.Group, data=covid1)
bptest(fitt)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fitt
## BP = 703.42, df = 7, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code>resids&lt;-fit2$residuals; fitvals&lt;-fit2$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-8-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>par(mfrow=c(1,2)); hist(resids); qqnorm(resids); qqline(resids, col=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-8-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ks.test(resids, &quot;pnorm&quot;, sd=sd(resids))</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.34713, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>sum((fitvals-mean(covid1$Total.Deaths))^2)/sum((covid1$Total.Deaths-mean(covid1$Total.Deaths))^2)</code></pre>
<pre><code>## [1] 0.6685351</code></pre>
<pre class="r"><code>#install.packages(&quot;sandwich&quot;)
library(sandwich)
coeftest(fit2)[,1:2]</code></pre>
<pre><code>## Estimate Std. Error
## (Intercept) 29.22345 111.1892
## COVID.19.Deaths 87.57734 101.0736
## Age.Group18-64 years 429.53386 149.5932
## Age.Group65 years and over 1181.55759 142.4399
## Age.GroupAll Ages 1556.13076 142.1918
## COVID.19.Deaths:Age.Group18-64 years -81.62083 101.0739
## COVID.19.Deaths:Age.Group65 years and over -83.22384
101.0736
## COVID.19.Deaths:Age.GroupAll Ages -82.83766 101.0736</code></pre>
<pre class="r"><code>coeftest(fit2, vcov = vcovHC(fit2))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 29.2234 1.9674 14.854 &lt; 2.2e-16 ***
## COVID.19.Deaths 87.5773 7.4137 11.813 &lt; 2.2e-16 ***
## Age.Group18-64 years 429.5339 37.8379 11.352 &lt; 2.2e-16
***
## Age.Group65 years and over 1181.5576 90.5492 13.049 &lt;
2.2e-16 ***
## Age.GroupAll Ages 1556.1308 118.8185 13.097 &lt; 2.2e-16
***
## COVID.19.Deaths:Age.Group18-64 years -81.6208 7.4214
-10.998 &lt; 2.2e-16 ***
## COVID.19.Deaths:Age.Group65 years and over -83.2238
7.4179 -11.219 &lt; 2.2e-16 ***
## COVID.19.Deaths:Age.GroupAll Ages -82.8377 7.4189
-11.166 &lt; 2.2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>66.6 percent of the variation is explained by the model. The histogram of residuals seems pretty normal but it did not meet the linearity assumption. The residuals are concentrated in one area so it is hard to tell it’s homoscedastic. The robust standard error did not change any coefficients but decreased the overall values of the standard errors.</p>
</div>
</div>
<div id="bootstrapped-standard-errors" class="section level1">
<h1>4. Bootstrapped Standard Errors</h1>
<pre class="r"><code>fit2 &lt;-lm(Total.Deaths ~ COVID.19.Deaths*Age.Group, data=covid1) 
resids&lt;-fit2$residuals 
fitted&lt;-fit2$fitted.values 

resid_resamp&lt;-replicate(5000,{
new_resids&lt;-sample(resids,replace=TRUE) #resample resids w/ replacement
new_y&lt;-fitted+new_resids #add new resids to yhats to get new &quot;data&quot;
fit&lt;-lm(new_y~COVID.19.Deaths*Age.Group,data=covid1) #refit model
coef(fit)
})

resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) COVID.19.Deaths Age.Group18-64 years
Age.Group65 years and over Age.GroupAll Ages
## 1 110.7463 98.94189 151.0157 142.3315 142.6786
## COVID.19.Deaths:Age.Group18-64 years
COVID.19.Deaths:Age.Group65 years and over
## 1 98.94131 98.94347
## COVID.19.Deaths:Age.GroupAll Ages
## 1 98.94282</code></pre>
<p>The standard errors were close to the ones before the robust standard errors were applied. It should provide lower p-values.</p>
</div>
<div id="logistic-regression" class="section level1">
<h1>5. Logistic Regression</h1>
<pre class="r"><code>data&lt;-covid1%&gt;%mutate(y=ifelse(MMWRyear==&quot;2020&quot;,1,0))
data$outcome&lt;-factor(covid1$MMWRyear,levels=c(&quot;2020&quot;,&quot;2021&quot;))
head(data)</code></pre>
<pre><code>## Data.As.Of Start.Week End.Week MMWRyear MMWRweek
Week.Ending.Date Group Indicator
## 1 04/29/2021 12/29/2019 01/04/2020 2020 1 01/04/2020 By
Week Week-ending
## 2 04/29/2021 12/29/2019 01/04/2020 2020 1 01/04/2020 By
Week Week-ending
## 3 04/29/2021 12/29/2019 01/04/2020 2020 1 01/04/2020 By
Week Week-ending
## 4 04/29/2021 12/29/2019 01/04/2020 2020 1 01/04/2020 By
Week Week-ending
## 5 04/29/2021 12/29/2019 01/04/2020 2020 1 01/04/2020 By
Week Week-ending
## 6 04/29/2021 12/29/2019 01/04/2020 2020 1 01/04/2020 By
Week Week-ending
## Jurisdiction Age.Group COVID.19.Deaths Total.Deaths
Pneumonia.Deaths Influenza.Deaths
## 1 United States All Ages 0 60029 4096 432
## 2 United States 0-17 years 0 669 19 22
## 3 United States 18-64 years 0 14707 764 183
## 4 United States 65 years and over 0 44653 3313 227
## 5 Alabama 0-17 years 0 16 0 0
## 6 Arizona 0-17 years 0 13 0 0
## Pneumonia.or.Influenza
Pneumonia..Influenza..or.COVID.19.Deaths Footnote y outcome
## 1 4528 4528 1 2020
## 2 41 41 1 2020
## 3 947 947 1 2020
## 4 3540 3540 1 2020
## 5 0 0 1 2020
## 6 0 0 1 2020</code></pre>
<pre class="r"><code>fit3&lt;-glm(y~ Total.Deaths + COVID.19.Deaths , family=&quot;binomial&quot;, data=data)
coeftest(fit3)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 1.0211e+00 2.6497e-02 38.5371 &lt; 2.2e-16 ***
## Total.Deaths 5.8718e-05 1.0273e-05 5.7159 1.091e-08 ***
## COVID.19.Deaths -2.7010e-04 4.5626e-05 -5.9199 3.221e-09
***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit3))</code></pre>
<pre><code>##     (Intercept)    Total.Deaths COVID.19.Deaths 
##       2.7763126       1.0000587       0.9997299</code></pre>
<pre class="r"><code>probs&lt;-predict(fit3,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=data$y)%&gt;%addmargins #confusion matrix </code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0      6   11   17
##     1   2135 6194 8329
##     Sum 2141 6205 8346</code></pre>
<pre class="r"><code>(6+6194)/8346 #accuracy</code></pre>
<pre><code>## [1] 0.7428708</code></pre>
<pre class="r"><code>6/17 #tpr(sensitivity)</code></pre>
<pre><code>## [1] 0.3529412</code></pre>
<pre class="r"><code>6194/8329 #tnr(specificity)</code></pre>
<pre><code>## [1] 0.7436667</code></pre>
<pre class="r"><code>6/2141 #ppv(precision)</code></pre>
<pre><code>## [1] 0.002802429</code></pre>
<p>The Total.Deaths increases the log-odds of year 2020 (more likely to be 2020), and COVID.19.Deaths decrease the log-odds for year 2020(more likely to be 2021). The odds of being year 2020 occurring at Total Deaths 0 is 2.776.
Going up 1 Total.Deaths multiplies odds by a factor of e^5.8718e-05 = 1.000. Going up 1 COVID.19.Deaths multiplies odds by a factor of e^-2.7010e-04 = 0.9997.</p>
<div id="density-plot" class="section level2">
<h2>Density Plot</h2>
<pre class="r"><code>logistic &lt;- function(x){exp(x)/(1+exp(x))} #inverse of the logit is the logistic
ggplot()+geom_function(fun=logistic)+xlim(-6,6)+xlab(&quot;t&quot;)+ylab(&quot;p( y = 1 )&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fit3&lt;-glm(y~ Total.Deaths + COVID.19.Deaths , family=&quot;binomial&quot;, data=data)

data$prob &lt;- predict(fit3,type=&quot;response&quot;) #get predicted probabilities
data$predicted &lt;- ifelse(data$prob&gt;.5,&quot;2020&quot;,&quot;2021&quot;) #get predicted outcomes

ggplot(data, aes(Total.Deaths + COVID.19.Deaths,y))+geom_jitter(aes(color=predicted),width=.5,height=0)+
  stat_smooth(method=&quot;glm&quot;,method.args=list(family=&quot;binomial&quot;),se=F)+ylab(&quot;2020 (0,1)&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-11-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>odds&lt;-function(p)p/(1-p)

p&lt;-seq(0,1,by=.1)
cbind(p, odds=odds(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds
##  [1,] 0.0 0.0000
##  [2,] 0.1 0.1111
##  [3,] 0.2 0.2500
##  [4,] 0.3 0.4286
##  [5,] 0.4 0.6667
##  [6,] 0.5 1.0000
##  [7,] 0.6 1.5000
##  [8,] 0.7 2.3333
##  [9,] 0.8 4.0000
## [10,] 0.9 9.0000
## [11,] 1.0    Inf</code></pre>
<pre class="r"><code>logit&lt;-function(p)log(odds(p))
cbind(p, odds=odds(p),logit=logit(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds   logit
##  [1,] 0.0 0.0000    -Inf
##  [2,] 0.1 0.1111 -2.1972
##  [3,] 0.2 0.2500 -1.3863
##  [4,] 0.3 0.4286 -0.8473
##  [5,] 0.4 0.6667 -0.4055
##  [6,] 0.5 1.0000  0.0000
##  [7,] 0.6 1.5000  0.4055
##  [8,] 0.7 2.3333  0.8473
##  [9,] 0.8 4.0000  1.3863
## [10,] 0.9 9.0000  2.1972
## [11,] 1.0    Inf     Inf</code></pre>
<pre class="r"><code>fit&lt;-glm(y~Total.Deaths + COVID.19.Deaths ,data=data,family=binomial(link=&quot;logit&quot;))

data$outcome&lt;-factor(data$outcome,levels=c(&quot;2020&quot;,&quot;2021&quot;)) #make it a factor for plotting
data$logit&lt;-predict(fit) #save predicted log-odds

logit&lt;-function(p)log(odds(p))
ggplot(data,aes(logit, fill=outcome))+geom_density(alpha=.3)+
  geom_vline(xintercept=0,lty=2)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-11-3.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="roc-curve-and-auc" class="section level2">
<h2>ROC Curve and AUC</h2>
<pre class="r"><code>#install.packages(&quot;plotROC&quot;)
library(plotROC) 

ROCplot&lt;-ggplot(data)+geom_roc(aes(d=outcome,m=prob), n.cuts=0) 

ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-12-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.4201373</code></pre>
<p>AUC is 0.42 and it is considered bad.</p>
</div>
</div>
<div id="logistic-regression-all-variables" class="section level1">
<h1>6. Logistic Regression: All Variables</h1>
<pre class="r"><code>data&lt;-covid1%&gt;%mutate(y=ifelse(MMWRyear==&quot;2020&quot;,1,0))

fit4 &lt;-glm(y ~ MMWRweek + Jurisdiction + Age.Group + COVID.19.Deaths + Total.Deaths + Pneumonia.Deaths + Influenza.Deaths + Pneumonia.or.Influenza + Pneumonia..Influenza..or.COVID.19.Deaths,data=data,family=&quot;binomial&quot;)
prob &lt;- predict(fit4,type=&quot;response&quot;)
probs&lt;-predict(fit,type=&quot;response&quot;)

class_diag &lt;- function(probs, truth) {
    # CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV
    
    if (is.character(truth) == TRUE) 
        truth &lt;- as.factor(truth)
    if (is.numeric(truth) == FALSE &amp; is.logical(truth) == FALSE) 
        truth &lt;- as.numeric(truth) - 1
    
    tab &lt;- table(factor(probs &gt; 0.5, levels = c(&quot;FALSE&quot;, &quot;TRUE&quot;)), 
        factor(truth, levels = c(0, 1)))
    acc = sum(diag(tab))/sum(tab)
    sens = tab[2, 2]/colSums(tab)[2]
    spec = tab[1, 1]/colSums(tab)[1]
    ppv = tab[2, 2]/rowSums(tab)[2]
    
    # CALCULATE EXACT AUC
    ord &lt;- order(probs, decreasing = TRUE)
    probs &lt;- probs[ord]
    truth &lt;- truth[ord]
    
    TPR = cumsum(truth)/max(1, sum(truth))
    FPR = cumsum(!truth)/max(1, sum(!truth))
    
    dup &lt;- c(probs[-1] &gt;= probs[-length(probs)], FALSE)
    TPR &lt;- c(0, TPR[!dup], 1)
    FPR &lt;- c(0, FPR[!dup], 1)
    n &lt;- length(TPR)
    auc &lt;- sum(((TPR[-1] + TPR[-n])/2) * (FPR[-1] - FPR[-n]))
    data.frame(acc, sens, spec, ppv, auc)
}

class_diag(prob, data$y)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.9537503 0.9661563 0.9177954 0.9714795 0.9835944</code></pre>
<p>The accuracy was 0.954, the sensitivity was 0.966, the specificity was 0.918, the precision was 0.971, and the AUC was 0.984. The AUC value is considered great.</p>
<div id="k-fold-cv" class="section level2">
<h2>K-fold CV</h2>
<pre class="r"><code>set.seed(1234)
k=10 #choose number of folds

data&lt;- covid1[sample(nrow(covid1)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(covid1)),breaks=k,labels=F) #create folds
data&lt;-covid1%&gt;%mutate(y=ifelse(MMWRyear==&quot;2020&quot;,1,0))

diags&lt;-NULL
for(i in 1:k){
  ## Create training and test sets
  train&lt;-data[folds!=i,] 
  test&lt;-data[folds==i,]
  
  truth&lt;-test$y ## Truth labels for fold i
  
  ## Train model on training set (all but fold i)
  fit&lt;-glm(y~Total.Deaths + COVID.19.Deaths,data=train,family=&quot;binomial&quot;)
  
  ## Test model on test set (fold i) 
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  
  ## Get diagnostics for fold i
  diags&lt;-rbind(diags,class_diag(probs,truth))
}


summarize_all(diags,mean) #average diagnostics across all k folds</code></pre>
<pre><code>##        acc sens spec       ppv       auc
## 1 0.741556  NaN  NaN 0.7434731 0.7460823</code></pre>
<pre class="r"><code>#install.packages(&quot;pROC&quot;)
library(pROC)  #Compare with this AUC calculator
auc(data$y, prob)</code></pre>
<pre><code>## Area under the curve: 0.9836</code></pre>
<p>The accuracy was 0.742 and the precision was 0.743. The AUC value was 0.746, which is considered poor. The area under the curve 0.984.</p>
</div>
<div id="lasso" class="section level2">
<h2>LASSO</h2>
<pre class="r"><code>#install.packages(&#39;glmnet&#39;)
library(glmnet)
set.seed(1234)

y &lt;- as.matrix(data$y)  #grab response
x &lt;- model.matrix(y ~  MMWRweek + Age.Group + COVID.19.Deaths + Total.Deaths + Pneumonia.Deaths + Influenza.Deaths + Pneumonia.or.Influenza + Pneumonia..Influenza..or.COVID.19.Deaths, data = data)[, -1]  #grab predictors
head(x)</code></pre>
<pre><code>## MMWRweek Age.Group18-64 years Age.Group65 years and over
Age.GroupAll Ages COVID.19.Deaths
## 1 1 0 0 1 0
## 2 1 0 0 0 0
## 3 1 1 0 0 0
## 4 1 0 1 0 0
## 5 1 0 0 0 0
## 6 1 0 0 0 0
## Total.Deaths Pneumonia.Deaths Influenza.Deaths
Pneumonia.or.Influenza
## 1 60029 4096 432 4528
## 2 669 19 22 41
## 3 14707 764 183 947
## 4 44653 3313 227 3540
## 5 16 0 0 0
## 6 13 0 0 0
## Pneumonia..Influenza..or.COVID.19.Deaths
## 1 4528
## 2 41
## 3 947
## 4 3540
## 5 0
## 6 0</code></pre>
<pre class="r"><code>x &lt;- scale(x)

cv &lt;- cv.glmnet(x, y, family = &quot;binomial&quot;)
lasso &lt;- glmnet(x, y, family = &quot;binomial&quot;, lambda = cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 11 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                                  s0
## (Intercept)                               6.2635058
## MMWRweek                                  5.3666649
## Age.Group18-64 years                     -0.6036176
## Age.Group65 years and over               -0.7258408
## Age.GroupAll Ages                        -0.8048060
## COVID.19.Deaths                          -9.4641481
## Total.Deaths                             -2.0334357
## Pneumonia.Deaths                         -7.1507500
## Influenza.Deaths                         19.1742536
## Pneumonia.or.Influenza                   -1.3689321
## Pneumonia..Influenza..or.COVID.19.Deaths 18.6944066</code></pre>
<p>I included the variables that do not have dates in them since these are the variables that are going to predict the year. All the variables showed non-zero coefficients.</p>
</div>
<div id="fold-cv-after-lasso" class="section level2">
<h2>10-fold CV after LASSO</h2>
<pre class="r"><code>set.seed(1234)
k=10 #choose number of folds

#select only rank1 indicator
data$y&lt;-ifelse(data$MMWRyear==&quot;2020&quot;,1,0)
data1&lt;-data[sample(nrow(data)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(data)),breaks=k,labels=F) #create folds

diags&lt;-NULL
for(i in 1:k){
  ## Create training and test sets
  train&lt;-data1[folds!=i,] 
  test&lt;-data1[folds==i,]
  truth&lt;-test$y
  
  ## Train model on training set
  fit&lt;-glm(y~MMWRweek + Age.Group + COVID.19.Deaths + Total.Deaths + Pneumonia.Deaths + Influenza.Deaths + Pneumonia.or.Influenza + Pneumonia..Influenza..or.COVID.19.Deaths,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  
  ## Test model on test set (save all k results)
  diags&lt;-rbind(diags,class_diag(probs,truth))
}

diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.9445252 0.9586271 0.9036929 0.9665345 0.9800764</code></pre>
<p>After performing the 10-fold CV using only the variables lasso selected, the AUC value was 0.98 which is higher than 0.743 above.</p>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
